package run

import (
	"context"
	"database/sql"
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"
)

// A receipt records why its run happened, and refuses to exist without one.
// #96 applies §2.6's intentionality rule to scheduling: a run nobody can name
// an authority for is a run nobody can be held to, so the record is where the
// claim becomes checkable rather than assumed.
func TestReceiptRequiresANameableAuthority(t *testing.T) {
	prep := mustPreparation(t, preparedAt, testSelection())
	for _, tc := range []struct {
		name string
		auth Authority
	}{
		{"none at all", Authority{}},
		{"a kind with no reference", Authority{Kind: AuthorityOperator}},
		{"a kind this build does not implement", Authority{Kind: "vibes", Ref: "why-not"}},
		{"a reference that is not an identifier", Authority{Kind: AuthorityPolicy, Ref: "two words"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := NewReceipt(NewReceiptID(), "run-1", prep, tc.auth, testBody(t), recorded); err == nil {
				t.Fatal("accepted a receipt whose run cannot be accounted for")
			}
		})
	}
	for _, auth := range []Authority{
		{Kind: AuthorityOperator, Ref: "invitation:inv-1"},
		{Kind: AuthorityPolicy, Ref: "memory-revisit"},
		{Kind: AuthoritySerendipity, Ref: "draw:d-1"},
	} {
		r, err := NewReceipt(NewReceiptID(), "run-1", prep, auth, testBody(t), recorded)
		if err != nil {
			t.Fatalf("refused authority %s: %v", auth, err)
		}
		if r.Header.Authority != auth {
			t.Errorf("stored authority = %+v, want %+v", r.Header.Authority, auth)
		}
		if !r.Header.Authority.Recorded() {
			t.Error("a receipt this build wrote reports no authority")
		}
	}
}

// A resumed run is the same run. The invitation or draw that authorized it does
// not become a different reason because the first attempt was interrupted, so an
// amendment inherits the authority instead of restating it — which is also what
// keeps the record of who started a run from being editable afterwards.
func TestAmendmentInheritsTheAuthority(t *testing.T) {
	ctx := context.Background()
	s := testStore(t)
	prep := mustPreparation(t, preparedAt, testSelection())
	draw := Authority{Kind: AuthoritySerendipity, Ref: "draw:d-7"}
	first, err := NewReceipt(NewReceiptID(), "run-1", prep, draw, testBody(t), recorded)
	if err != nil {
		t.Fatalf("NewReceipt: %v", err)
	}
	if err := s.PutReceipt(ctx, first); err != nil {
		t.Fatalf("PutReceipt: %v", err)
	}
	body := testBody(t)
	body.AmendmentReason = "the run was resumed after an interruption"
	second, err := Amend(first, NewReceiptID(), body, recorded.Add(1))
	if err != nil {
		t.Fatalf("Amend: %v", err)
	}
	if second.Header.Authority != draw {
		t.Errorf("amended authority = %+v, want the prior revision's %+v", second.Header.Authority, draw)
	}
	if err := s.PutReceipt(ctx, second); err != nil {
		t.Fatalf("PutReceipt amendment: %v", err)
	}
	chain, err := s.Revisions(ctx, "run-1")
	if err != nil {
		t.Fatalf("Revisions: %v", err)
	}
	for i, r := range chain {
		if r.Header.Authority != draw {
			t.Errorf("revision %d authority = %+v, want %+v", i+1, r.Header.Authority, draw)
		}
	}
}

// schemaV1 is the run component's schema exactly as version 1 created it: no
// authority columns, and an immutability trigger that names the columns that
// existed then. It is written out literally rather than derived from the current
// constant, because a migration test whose "old" database is generated by the
// new code is testing nothing.
const schemaV1 = `
CREATE TABLE IF NOT EXISTS run_preparation(
	id             TEXT PRIMARY KEY,
	schema_version INTEGER NOT NULL,
	prepared_at    TEXT NOT NULL,
	source_count   INTEGER NOT NULL,
	sync_state     TEXT NOT NULL CHECK (sync_state IN ('pending-sync', 'committed')),
	payload        BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS run_receipt(
	id             TEXT PRIMARY KEY,
	schema_version INTEGER NOT NULL,
	run_id         TEXT NOT NULL,
	preparation_id TEXT NOT NULL REFERENCES run_preparation(id),
	revision       INTEGER NOT NULL,
	supersedes     TEXT REFERENCES run_receipt(id),
	recorded_at    TEXT NOT NULL,
	sync_state     TEXT NOT NULL CHECK (sync_state IN ('pending-sync', 'committed')),
	counts         TEXT NOT NULL,
	payload        BLOB NOT NULL,
	UNIQUE(run_id, revision),
	UNIQUE(supersedes)
);

CREATE INDEX IF NOT EXISTS run_receipt_run_idx ON run_receipt(run_id, revision);

CREATE TRIGGER IF NOT EXISTS run_preparation_immutable
BEFORE UPDATE OF id, schema_version, prepared_at, source_count, payload ON run_preparation
BEGIN SELECT RAISE(ABORT, 'preparation records are immutable'); END;

CREATE TRIGGER IF NOT EXISTS run_preparation_append_only
BEFORE DELETE ON run_preparation
BEGIN SELECT RAISE(ABORT, 'preparation records are append-only'); END;

CREATE TRIGGER IF NOT EXISTS run_receipt_immutable
BEFORE UPDATE OF id, schema_version, run_id, preparation_id, revision, supersedes,
	recorded_at, counts, payload ON run_receipt
BEGIN SELECT RAISE(ABORT, 'run receipts are immutable'); END;

CREATE TRIGGER IF NOT EXISTS run_receipt_append_only
BEFORE DELETE ON run_receipt
BEGIN SELECT RAISE(ABORT, 'run receipts are append-only'); END;`

// A database written before the authority column existed still opens, and its
// receipts still read — carrying no authority, which is the truth about them.
// Nothing is backfilled: those runs happened before anything was recording why,
// and writing "operator" over them would manufacture the provenance the column
// exists to carry.
func TestUpgradeFromVersionOneLeavesEarlierRunsUnattributed(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	path := filepath.Join(dir, DatabaseName)

	// A receipt built by this build, stored the way version 1 stored one.
	prep := mustPreparation(t, preparedAt, testSelection())
	legacy, err := NewReceipt(NewReceiptID(), "run-legacy", prep,
		Authority{Kind: AuthorityOperator, Ref: "command:explore"}, testBody(t), recorded)
	if err != nil {
		t.Fatalf("NewReceipt: %v", err)
	}
	payload, err := legacy.MarshalBody()
	if err != nil {
		t.Fatalf("MarshalBody: %v", err)
	}
	counts, err := json.Marshal(legacy.Header.Counts)
	if err != nil {
		t.Fatalf("encode counts: %v", err)
	}
	prepPayload, err := prep.MarshalCanonical()
	if err != nil {
		t.Fatalf("MarshalCanonical: %v", err)
	}

	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("open the old database: %v", err)
	}
	if _, err := db.Exec(schemaV1); err != nil {
		t.Fatalf("create the version 1 schema: %v", err)
	}
	if _, err := db.Exec(`CREATE TABLE IF NOT EXISTS schema_migration(
		component TEXT PRIMARY KEY, version INTEGER NOT NULL)`); err != nil {
		t.Fatalf("create the migration ledger: %v", err)
	}
	if _, err := db.Exec(`INSERT INTO schema_migration(component, version) VALUES(?, 1)`,
		storeComponent); err != nil {
		t.Fatalf("record version 1: %v", err)
	}
	if _, err := db.Exec(`INSERT INTO run_preparation(
		id, schema_version, prepared_at, source_count, sync_state, payload)
		VALUES(?, ?, ?, ?, ?, ?)`, string(prep.ID), prep.Schema, formatTime(prep.PreparedAt),
		len(prep.Selection), SyncPending, prepPayload); err != nil {
		t.Fatalf("insert the old preparation: %v", err)
	}
	if _, err := db.Exec(`INSERT INTO run_receipt(
		id, schema_version, run_id, preparation_id, revision, supersedes,
		recorded_at, sync_state, counts, payload) VALUES(?, ?, ?, ?, ?, NULL, ?, ?, ?, ?)`,
		string(legacy.Header.ID), legacy.Header.Schema, legacy.Header.RunID,
		string(prep.ID), 1, formatTime(legacy.Header.RecordedAt), SyncPending,
		counts, payload); err != nil {
		t.Fatalf("insert the old receipt: %v", err)
	}
	if err := db.Close(); err != nil {
		t.Fatalf("close the old database: %v", err)
	}

	s, err := Open(dir)
	if err != nil {
		t.Fatalf("Open an upgradable database: %v", err)
	}
	defer s.Close()

	var version int
	if err := s.db.QueryRow(`SELECT version FROM schema_migration WHERE component = ?`,
		storeComponent).Scan(&version); err != nil {
		t.Fatalf("read the migrated version: %v", err)
	}
	if version != storeVersion {
		t.Errorf("migrated version = %d, want %d", version, storeVersion)
	}

	before, err := s.Receipt(ctx, legacy.Header.ID)
	if err != nil {
		t.Fatalf("read the pre-authority receipt: %v", err)
	}
	if before.Header.Authority.Recorded() {
		t.Errorf("a pre-authority receipt claims authority %+v", before.Header.Authority)
	}
	if before.Header.Authority.String() != "unrecorded" {
		t.Errorf("rendered authority = %q, want %q", before.Header.Authority.String(), "unrecorded")
	}
	if before.Header.RunID != "run-legacy" || before.Body.Worker == nil {
		t.Errorf("the migration damaged the receipt: %+v", before.Header)
	}

	// The migrated database still refuses to have its receipts rewritten,
	// including through the columns the migration added.
	if _, err := s.db.Exec(`UPDATE run_receipt SET authority_kind = ? WHERE id = ?`,
		string(AuthorityOperator), string(legacy.Header.ID)); err == nil {
		t.Error("the migrated database allowed a receipt's authority to be edited")
	} else if !strings.Contains(err.Error(), "immutable") {
		t.Errorf("editing a migrated receipt failed with %v, want the immutability trigger", err)
	}

	// And a run recorded after the upgrade carries its own authority.
	fresh, err := NewReceipt(NewReceiptID(), "run-after", prep,
		Authority{Kind: AuthoritySerendipity, Ref: "draw:d-1"}, testBody(t), recorded)
	if err != nil {
		t.Fatalf("NewReceipt after upgrade: %v", err)
	}
	if err := s.PutReceipt(ctx, fresh); err != nil {
		t.Fatalf("PutReceipt after upgrade: %v", err)
	}
	stored, err := s.Receipt(ctx, fresh.Header.ID)
	if err != nil {
		t.Fatalf("read the new receipt: %v", err)
	}
	if stored.Header.Authority != fresh.Header.Authority {
		t.Errorf("authority round-tripped as %+v, want %+v",
			stored.Header.Authority, fresh.Header.Authority)
	}
}
