package cookbook

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"

	"github.com/atyrode/babel/internal/digest"
)

// manifestFile is the committed version record beside the recipes.
const manifestFile = "versions.json"

// manifestSchema versions the record's own shape, independently of the recipe
// versions it holds. Schema 2 added the cookbook's own statement, which is
// versioned under the same rule as a recipe.
const manifestSchema = 2

// Manifest is the committed record of the statement's and each recipe's
// declared version and content digest.
//
// It exists because §5.1's rule — "semantic behaviour changes require a
// recipe-version increment" — is otherwise unenforceable: the working tree
// alone cannot tell an edited body from an original one. The manifest is the
// prior state to compare against, so an undeclared change becomes a
// mechanical, reviewable failure rather than something a reader must notice in
// a diff. It is committed with the recipes and regenerated by WriteManifest
// whenever a version is legitimately incremented.
type Manifest struct {
	Schema int `json:"manifest_schema"`
	// Preamble records the cookbook's statement. It is a field rather than a
	// recipe entry because it is not a recipe — no run is briefed with it —
	// while being exactly as version-bound: it is the standard recipe changes
	// are reviewed against, and a standard that could be rewritten silently
	// would make every review that cited it cite text that is gone.
	Preamble PreambleEntry   `json:"preamble"`
	Recipes  []ManifestEntry `json:"recipes"`
}

// ManifestEntry records one recipe's declared version and the digest of the
// content that version describes.
type ManifestEntry struct {
	ID      string        `json:"id"`
	Version int           `json:"version"`
	Digest  digest.Digest `json:"digest"`
}

// PreambleEntry records the statement's declared version and content digest.
// It carries no id: the cookbook has exactly one statement, and a name that
// could only ever hold one value is a field nobody may edit.
type PreambleEntry struct {
	Version int           `json:"version"`
	Digest  digest.Digest `json:"digest"`
}

// NewManifest records the current state of a loaded set.
func NewManifest(s *Set) Manifest {
	m := Manifest{
		Schema:   manifestSchema,
		Preamble: PreambleEntry{Version: s.preamble.Version, Digest: s.preamble.Digest},
		Recipes:  make([]ManifestEntry, 0, len(s.recipes)),
	}
	for _, r := range s.recipes {
		m.Recipes = append(m.Recipes, ManifestEntry{ID: r.ID, Version: r.Version, Digest: r.Digest})
	}
	return m
}

// LoadManifest reads the version record from an asset tree. Decoding is strict:
// an unknown field means the file was written by something that knows a shape
// this build does not, and silently ignoring it would let the drift check pass
// on a record it only partly understands.
func LoadManifest(fsys fs.FS) (Manifest, error) {
	var m Manifest
	data, err := fs.ReadFile(fsys, manifestFile)
	if err != nil {
		return m, fmt.Errorf("read cookbook %s: %w", manifestFile, err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&m); err != nil {
		return m, fmt.Errorf("decode cookbook %s: %w", manifestFile, err)
	}
	if m.Schema != manifestSchema {
		return m, fmt.Errorf("cookbook %s: manifest schema %d, this build writes %d", manifestFile, m.Schema, manifestSchema)
	}
	switch {
	case m.Preamble.Version < 1:
		return m, fmt.Errorf("cookbook %s: the %s entry has version %d, want at least 1", manifestFile, preambleID, m.Preamble.Version)
	case !m.Preamble.Digest.Valid():
		return m, fmt.Errorf("cookbook %s: the %s entry has a malformed digest", manifestFile, preambleID)
	}
	for i, e := range m.Recipes {
		switch {
		case !validID(e.ID):
			return m, fmt.Errorf("cookbook %s: entry %d has invalid id %q", manifestFile, i, e.ID)
		case e.ID == preambleID:
			return m, fmt.Errorf("cookbook %s: entry %d takes id %q, which the cookbook's own statement is recorded under", manifestFile, i, e.ID)
		case e.Version < 1:
			return m, fmt.Errorf("cookbook %s: entry %q has version %d, want at least 1", manifestFile, e.ID, e.Version)
		case !e.Digest.Valid():
			return m, fmt.Errorf("cookbook %s: entry %q has a malformed digest", manifestFile, e.ID)
		}
	}
	return m, nil
}

// Canonical renders the manifest as the committed file's exact bytes: schema
// first, then the statement, then the recipes sorted by id, two-space
// indentation, trailing newline. A canonical form means regeneration produces
// no incidental diff, so a manifest diff is always a real version or content
// change.
func (m Manifest) Canonical() ([]byte, error) {
	// An empty list is encoded as [] rather than null so the file's shape
	// never depends on how many recipes ship.
	out := Manifest{Schema: manifestSchema, Preamble: m.Preamble, Recipes: make([]ManifestEntry, 0, len(m.Recipes))}
	out.Recipes = append(out.Recipes, m.Recipes...)
	sort.Slice(out.Recipes, func(i, j int) bool { return out.Recipes[i].ID < out.Recipes[j].ID })
	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode cookbook manifest: %w", err)
	}
	return append(data, '\n'), nil
}

// WriteManifest regenerates dir's version record from the statement and the
// recipes in dir. It is the authoring step that follows a deliberate version
// increment, and the only sanctioned way to make a drift report go away.
func WriteManifest(dir string) error {
	set, err := LoadDir(dir)
	if err != nil {
		return err
	}
	data, err := NewManifest(set).Canonical()
	if err != nil {
		return err
	}
	path := filepath.Join(dir, manifestFile)
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// DriftKind classifies one disagreement between the cookbook's documents and
// their version record.
type DriftKind string

// The drift kinds. Only DriftUndeclared is a §5.1 violation; the others are
// the ways the record itself stops describing the recipes, and each of them
// would blind the check to a later undeclared change.
const (
	// DriftUndeclared is the rule §5.1 states: content changed while the
	// declared version stayed the same.
	DriftUndeclared DriftKind = "undeclared-change"

	// DriftRegressed is a version that moved backwards, which would let an
	// earlier version's guidance be recorded under a version already used.
	DriftRegressed DriftKind = "version-regressed"

	// DriftStale is a legitimately incremented version whose new content was
	// never recorded. The change is declared; the record needs regenerating.
	DriftStale DriftKind = "stale-record"

	// DriftUnrecorded is a recipe absent from the record, so nothing
	// constrains its next edit.
	DriftUnrecorded DriftKind = "unrecorded-recipe"

	// DriftDropped is a recorded recipe that no longer exists.
	DriftDropped DriftKind = "dropped-recipe"
)

// Drift is one reported disagreement.
type Drift struct {
	ID     string
	Kind   DriftKind
	Detail string
}

func (d Drift) String() string {
	return fmt.Sprintf("%s: %s: %s", d.ID, d.Kind, d.Detail)
}

// Check compares a loaded set against the manifest and reports every
// disagreement, ordered by id. An empty result is the committed state: the
// statement and every recipe recorded, every digest matching its declared
// version.
func (m Manifest) Check(s *Set) []Drift {
	recorded := make(map[string]ManifestEntry, len(m.Recipes))
	for _, e := range m.Recipes {
		recorded[e.ID] = e
	}

	var drifts []Drift
	if d, ok := compare(preambleID, s.preamble.Version, s.preamble.Digest,
		m.Preamble.Version, m.Preamble.Digest); ok {
		drifts = append(drifts, d)
	}
	for _, r := range s.recipes {
		entry, ok := recorded[r.ID]
		if !ok {
			drifts = append(drifts, Drift{
				ID:     r.ID,
				Kind:   DriftUnrecorded,
				Detail: fmt.Sprintf("recipe is not in %s; regenerate the version record", manifestFile),
			})
			continue
		}
		delete(recorded, r.ID)
		if d, ok := compare(r.ID, r.Version, r.Digest, entry.Version, entry.Digest); ok {
			drifts = append(drifts, d)
		}
	}

	for id, entry := range recorded {
		drifts = append(drifts, Drift{
			ID:     id,
			Kind:   DriftDropped,
			Detail: fmt.Sprintf("version %d is recorded but the recipe is gone", entry.Version),
		})
	}
	sort.Slice(drifts, func(i, j int) bool { return drifts[i].ID < drifts[j].ID })
	return drifts
}

// compare reports how one document's declared version and content digest
// disagree with what the record holds for it, and whether they disagree at
// all. It is one function for the statement and for every recipe because
// §5.1's rule is one rule: a digest that moved under a version that did not is
// an undeclared change wherever it happens.
func compare(id string, version int, content digest.Digest, recordedVersion int, recordedDigest digest.Digest) (Drift, bool) {
	switch {
	case content == recordedDigest && version == recordedVersion:
		return Drift{}, false
	case version < recordedVersion:
		return Drift{
			ID:     id,
			Kind:   DriftRegressed,
			Detail: fmt.Sprintf("version %d is below the recorded %d", version, recordedVersion),
		}, true
	case content == recordedDigest:
		return Drift{
			ID:     id,
			Kind:   DriftStale,
			Detail: fmt.Sprintf("version moved from %d to %d with no content change to declare", recordedVersion, version),
		}, true
	case version == recordedVersion:
		return Drift{
			ID:     id,
			Kind:   DriftUndeclared,
			Detail: fmt.Sprintf("content changed while version stayed at %d; §5.1 requires an increment", version),
		}, true
	default:
		return Drift{
			ID:     id,
			Kind:   DriftStale,
			Detail: fmt.Sprintf("version %d declares content the record does not have; regenerate it", version),
		}, true
	}
}

// Verify loads an asset tree with its version record and reports every drift.
// It is the whole enforcement surface: one call in a test or a check command
// is what keeps §5.1's versioning rule real.
func Verify(fsys fs.FS) ([]Drift, error) {
	set, err := Load(fsys)
	if err != nil {
		return nil, err
	}
	m, err := LoadManifest(fsys)
	if err != nil {
		return nil, err
	}
	return m.Check(set), nil
}
